src/app/globals.css, tailwind.config.ts
=> added setting

src/lib/create-safe-context.ts
안전한 리액트 ContextProvider와 커스텀훅을 만들어주는 `createSafeContext`를 추가했어요.
```ts
/**
* 안전한 컨텍스트와 훅을 생성합니다
* - Provider 없이 사용할 경우 에러가 발생합니다
*
* @param init - 컨텍스트 초기값
* @returns [useSafeContext, Provider]
* @example
* const [useSome, SomeContextProvider] = createSafeContext<SomeContextType>();
*/
export function createSafeContext<T>(init?: T) {
const context = createContext(init);
const useSafeContext = () => {
const ctx = useContext(context);
if (!ctx) {
throw new Error("useSafeContext must be used within a Provider");
}
return ctx;
};
return [useSafeContext, context.Provider] as const;
}
```
React에서 Context API를 사용할 때 다음처럼 사용하는데요:
```ts
const UserContext = createContext<{ username: string } | undefined>(undefined);
function ParentComponent() {
const [username, setUsername] = useState("John"); …
```
=> createSafeContext 추가

package-lock.json, package.json
=> clsx, tailwind-merge를 devDependencies에서 dependencies로 이동

src/components/ui/button.tsx
ui: button focus 제거 후 actvie 상태에서 스타일 효과 추가
#17
=> ui: button focus 제거 후 actvie 상태에서 스타일 효과 추가

src/app/(auth)/design/page.tsx, src/app/(auth)/links/page.tsx, src/components/ui/app-header.tsx, src/components/ui/button.tsx
AppHeader 컴포넌트 구현
```ts
<AppHeader>
<AppHeaderLeft>
left
</AppHeaderLeft>
<AppHeaderCenter>
center
</AppHeaderCenter>
<AppHeaderRight>
right
</AppHeaderRight>
</AppHeader>
```
#26
=> AppHeader 컴포넌트

src/app/(public)/userscreen/page.tsx
추가로 수정해야할 부분 생기면 수정하겠습니다 --> 완성 디자인은 임의로 기본적으로 깔끔하게 만들었습니다
=> userscreen 퍼블리싱

src/components/ui/card.tsx
padding 값 전달해서 사용하도록, vriant 기본값 default 변경
패딩을 원하는대로 조절할 수 있어요
=> feat : padding, 기본값 수정

package-lock.json, package.json, src/app/signup/link/page.tsx, src/app/signup/welcome/page.tsx
signup/link/page.tsx : 계정생성 중 링크등록 페이지
signup/welcome/page.tsx : 계정생성 완료 페이지
#36 
* 라우팅 네이밍은 임의 생성했습니다. 추후 로그인 페이지에 따라 변경 예정.
* SNS별 링크 연결 아이콘 캐러셀 추가 예정.
=> 링크등록화면 퍼블리싱

package-lock.json, package.json, src/app/(auth)/links/page.tsx, src/components/link-editor.tsx
#37 
https://github.com/user-attachments/assets/e649a12a-945b-4bd2-a120-690d4fcf30d2
PC 드래그
https://github.com/user-attachments/assets/c859674b-8c6a-4fcd-b927-63b7e5888a99
모바일 드래그
https://github.com/user-attachments/assets/7f3c8bd4-2f96-4a07-b908-1c0d39a8735e
=> feat: 링크 블록 컴포넌트 기본구현

src/components/portal.tsx, src/components/ui/backdrop.tsx, src/components/ui/modal.tsx
- [react portal 컴포넌트](https://github.com/2hundred2ne2/in_my_link/commit/d0023029ed6102b7e3201390ad962ec322ffdebc)
- [Modal 컴포넌트를 구현](https://github.com/2hundred2ne2/in_my_link/commit/cdefc80c87480d6dc2a69658a236c8d07f3a078d)
```tsx
const [isModalOpen, setIsModalOpen] = useState(false);
return (
<>
<button onClick={() => setIsModalOpen(true)}>show</button>
<Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)}>
<p>여기에 모달 내용을 넣으세요.</p>
</Modal>
;
</>
);
```
#43 
https://github.com/user-attachments/assets/2e81184b-b3bf-40c6-94b8-cb08ee12bb64
=> Modal 컴포넌트

src/app/(auth)/profile/page.tsx, src/components/ui/textarea.tsx
=> ui: textarea 컴포넌트

src/app/(public)/signup/profile/page.tsx
=> feat: 회원가입 > 정보입력 페이지 추가

.env.example, README.md, package-lock.json, package.json, src/lib/db.ts
```ts
import { query, trx } from "@/lib/db";
const books = await query<User[]>('SELECT * FROM book WHERE count > ?', [10]);
const result = await trx(async (connection) => {
await connection.query('INSERT INTO users (name) VALUES (?)', ['John']);
await connection.query('UPDATE accounts SET balance = balance - 100 WHERE user_id = ?', [1]);
return { success: true };
});
```
#57 
README에 DB 설정 방법을 추가했어요
=> DB 설정 및 `query`, `trx`(트랜잭션) 함수 구현

src/app/(public)/signup/page.tsx
=> feat:회원가입 퍼블리싱 수정

src/app/api/links/reorder/route.ts, src/components/link-editor.tsx
=> 링크 순서 변경 API

src/app/api/links/[id]/route.ts, src/app/api/links/route.ts
=> 링크 업데이트 API

src/app/api/button-config/route.ts, src/app/api/links/[id]/route.ts
=> 버튼 설정 조회 API

src/app/api/button-config/route.ts
=> 버튼 설정 업데이트 API

src/app/api/skin-config/route.ts
=> 스킨 설정 조회 API

src/app/api/font-config/route.ts
=> 폰트 설정 조회 API 

src/app/api/button-config/route.ts, src/app/api/font-config/route.ts, src/app/api/skin-config/route.ts
=> 폰트 업데이트 API

src/app/api/skin-config/route.ts
=> 스킨 설정 업데이트 API

src/app/(auth)/design/page.tsx
=> design page option UI

.eslintrc.js, .prettierignore, package-lock.json, package.json, prettier.config.js, src/app/(auth)/design/page.tsx, src/app/(auth)/layout.tsx, src/app/(auth)/links/page.tsx, src/app/(auth)/profile/page.tsx, src/app/(public)/page.tsx, src/app/(public)/signup/link/page.tsx, src/app/(public)/signup/page.tsx, src/app/(public)/signup/profile/page.tsx, src/app/(public)/signup/welcome/page.tsx, src/app/(public)/userscreen/page.tsx, src/app/layout.tsx, src/components/input.tsx, src/components/links/link-list-editor.tsx, src/components/links/link-list-item.tsx, src/components/mobile-navigation.tsx, src/components/ui/app-header.tsx, src/components/ui/button.tsx, src/components/ui/editable-text.tsx, src/components/ui/modal.tsx, src/components/ui/tabs.tsx, src/components/ui/toast.tsx
=> 린트 any 경고 처리

.env.example, src/app/(auth)/links/page.tsx, src/app/api/links/[id]/route.ts, src/app/api/links/reorder/route.ts, src/app/api/links/route.ts, src/components/links/link-add-modal.tsx, src/components/links/link-delete-modal.tsx, src/components/links/link-list-editor.tsx, src/components/links/link-list-item.tsx, src/components/links/linke-image-delete-modal.tsx, src/components/ui/editable-text.tsx, src/constants/env.ts, src/lib/db.ts
- 링크 관리 API 연동
DB 빈데이터 확인 -> 제목변경 -> URL 변경 -> 이미지 제거 -> 순서 변경후 새로고침 3번
https://github.com/user-attachments/assets/0e7f2370-38e4-4989-bddf-e7943627d58e
`.env.local` 파일에 다음 추가해주셔야해요
```
NEXT_PUBLIC_API_URL=http://localhost:3000
```
=> 링크 관리 API 연동

src/app/(auth)/links/page.tsx, src/app/api/button-config/route.ts, src/app/api/font-config/route.ts, src/app/api/links/route.ts, src/app/api/skin-config/route.ts, src/types/button-config.ts, src/types/font-config.ts, src/types/skin-config.ts
- 링크 추가 API를 배열로 등록할 수 있게 수정
#59
=> 링크 추가시 배열로 등록

package-lock.json, package.json, src/app/layout.tsx, src/components/links/link-list-editor.tsx, src/components/links/link-list-item.tsx, src/components/mobile-navigation.tsx, src/components/ui/app-header.tsx, src/components/ui/editable-text.tsx
- 링크 관리 유효성검사
- react-hot-toast 추가
- 전체 max-w-sm으로 하향 수정
#37 
https://github.com/user-attachments/assets/1751828a-19ca-4544-a3b2-000b0d7da785
=> 링크 관리 유효성검사

src/app/(auth)/links/page.tsx, src/components/ui/avatar.tsx, src/components/user-profile.tsx
- Avatar 컴포넌트 구현
- UserProfile 컴포넌트 구현
- 사용자 프로필
- 닉네임
- 자기소개
#110
=> Avatar 컴포넌트

src/components/design/font-config-editor.tsx, src/components/design/layout-config-editor.tsx, src/components/design/skin-config-editor.tsx, src/components/linklayout.tsx
=> 링크 컴포넌트 수정

src/components/signup/link-list-editor.tsx
=> fix: user id 넣기
